# -*- coding: utf-8 -*-
"""Portfolio Advisory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcMY4oldobHzE2inhmtDQOyGQA1ejVoW

#Portfolio Advisory
"""

# ================================================================
# AI Portfolio Advisory System —
# Modular Architecture + Explainability Layer + Interactive CLI
# ================================================================

from typing import Dict, List, Optional, Tuple, Any
import numpy as np
import pandas as pd
from fastapi import FastAPI
from pydantic import BaseModel, Field, field_validator

# Optional imports (safe fallbacks if unavailable)
try:
    from statsmodels.tsa.arima.model import ARIMA
except Exception:
    ARIMA = None

try:
    from sklearn.linear_model import LinearRegression
    from sklearn.preprocessing import StandardScaler
except Exception:
    LinearRegression = None
    StandardScaler = None

try:
    import scipy.optimize as sco
except Exception:
    sco = None

try:
    import tensorflow as tf
    from tensorflow.keras import layers, models
except Exception:
    tf = None
    layers = None
    models = None


# -----------------------------
# Risk Profiler
# -----------------------------
class RiskProfiler:
    RISK_TOLERANCE_MAP = {"low": 0.2, "medium": 0.5, "high": 0.8}

    def __init__(self, weight_risk_pref=0.6, weight_horizon=0.3, weight_s2i=0.1):
        self.w_risk = weight_risk_pref
        self.w_horizon = weight_horizon
        self.w_s2i = weight_s2i

    def score(self, risk_tolerance, horizon_years, savings_to_income=None):
        rt_val = self.RISK_TOLERANCE_MAP.get(risk_tolerance.lower(), 0.5)
        horizon_score = np.clip(horizon_years / 30.0, 0.0, 1.0)
        s2i_score = np.clip(savings_to_income or 0.2, 0.0, 1.0)
        raw = self.w_risk * rt_val + self.w_horizon * horizon_score + self.w_s2i * s2i_score
        return float(np.clip(raw, 0.0, 1.0))


# -----------------------------
# Sentiment Analyzer (stub)
# -----------------------------
class SentimentAnalyzer:
    def __init__(self, model_name=None):
        self.model_name = model_name or "finbert-stub"

    def score_texts(self, texts):
        if len(texts) == 0:
            return []
        rng = np.random.RandomState(42)
        return list(rng.uniform(-0.2, 0.2, size=len(texts)))


# -----------------------------
# Market Forecaster
# -----------------------------
class MarketForecaster:
    def __init__(self):
        self.scaler = StandardScaler() if StandardScaler is not None else None

    @staticmethod
    def _annualize_returns(daily_returns, periods_per_year=252):
        mean_daily = np.nanmean(daily_returns)
        vol_daily = np.nanstd(daily_returns, ddof=1)
        mean_ann = (1 + mean_daily) ** periods_per_year - 1
        vol_ann = vol_daily * np.sqrt(periods_per_year)
        return float(mean_ann), float(vol_ann)

    def forecast_arima(self, asset_series, steps=252):
        if asset_series.dropna().shape[0] < 10 or ARIMA is None:
            returns = asset_series.pct_change().dropna().values
            return self._annualize_returns(returns)
        try:
            y = np.log(asset_series.dropna())
            model = ARIMA(y, order=(1, 1, 0))
            fitted = model.fit()
            forecast_log = fitted.forecast(steps=steps)
            daily_forecast_returns = np.diff(forecast_log) / forecast_log[:-1]
            return self._annualize_returns(daily_forecast_returns)
        except Exception:
            returns = asset_series.pct_change().dropna().values
            return self._annualize_returns(returns)

    def forecast_lstm(self, asset_series, n_past=60, n_future=21, epochs=5, batch_size=16):
        returns = asset_series.pct_change().dropna()
        if tf is None or len(returns) < n_past + 10:
            return self._annualize_returns(returns.values)
        try:
            data = returns.values.reshape(-1, 1)
            scaler = self.scaler or StandardScaler()
            data_scaled = scaler.fit_transform(data)

            X, y = [], []
            for i in range(n_past, len(data_scaled)):
                X.append(data_scaled[i - n_past:i, 0])
                y.append(data_scaled[i, 0])
            X = np.array(X)
            y = np.array(y)
            X = X.reshape((X.shape[0], X.shape[1], 1))

            model = models.Sequential([
                layers.Input(shape=(X.shape[1], 1)),
                layers.LSTM(16, activation="tanh"),
                layers.Dense(1)
            ])
            model.compile(optimizer="adam", loss="mse")
            model.fit(X, y, epochs=epochs, batch_size=batch_size, verbose=0)

            seq = data_scaled[-n_past:].reshape(1, n_past, 1)
            preds = []
            for _ in range(n_future):
                p = model.predict(seq, verbose=0)[0, 0]
                preds.append(p)
                seq = np.roll(seq, -1, axis=1)
                seq[0, -1, 0] = p
            preds = scaler.inverse_transform(np.array(preds).reshape(-1, 1)).flatten()
            return self._annualize_returns(preds)
        except Exception:
            return self._annualize_returns(returns.values)

    def batch_forecast(self, price_df, method_map=None):
        results = {}
        for col in price_df.columns:
            series = price_df[col].dropna()
            method = (method_map or {}).get(col, "lstm" if series.pct_change().std() > 0.03 else "arima")
            if method == "arima":
                exp_r, vol = self.forecast_arima(series)
            elif method == "lstm":
                exp_r, vol = self.forecast_lstm(series)
            else:
                exp_r, vol = self._annualize_returns(series.pct_change().dropna().values)
            results[col] = {"expected_return": exp_r, "volatility": vol}
        return results


# -----------------------------
# Portfolio Optimizer (MPT)
# -----------------------------
class PortfolioOptimizer:
    def __init__(self, risk_free_rate=0.06):
        self.rf = risk_free_rate

    def maximize_sharpe(self, expected_returns, cov, bounds=None):
        if sco is None:
            raise RuntimeError("scipy is required for optimization")
        n = len(expected_returns)
        if bounds is None:
            bounds = tuple((0.0, 1.0) for _ in range(n))

        def portfolio_perf(w):
            ret = np.dot(w, expected_returns)
            vol = np.sqrt(w.T @ cov @ w)
            sharpe = (ret - self.rf) / vol if vol > 0 else 0
            return ret, vol, sharpe

        def neg_sharpe(w):
            return -portfolio_perf(w)[2]

        cons = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1},)
        x0 = np.ones(n) / n
        opt = sco.minimize(neg_sharpe, x0, bounds=bounds, constraints=cons, method="SLSQP")
        w = np.clip(opt.x, 0, 1)
        ret, vol, sharpe = portfolio_perf(w)
        return {"weights": w, "return": ret, "volatility": vol, "sharpe": sharpe}


# -----------------------------
# Explainability Engine
# -----------------------------
class ExplainabilityEngine:
    @staticmethod
    def explain(user_input, portfolio_metrics, allocations):
        risk = user_input["risk_tolerance"].capitalize()
        goal = user_input["goal"].capitalize()
        risk_score = portfolio_metrics["risk_score"]
        sharpe = portfolio_metrics["sharpe"]

        # Base rationale
        reasoning = f"Based on your **{risk.lower()} risk tolerance** and a goal of **{goal.lower()}**, "
        if risk_score < 0.4:
            reasoning += "the system prioritized stability and lower volatility assets like Fixed Deposits and Mutual Funds. "
        elif risk_score < 0.7:
            reasoning += "the portfolio strikes a balance between safety and growth by mixing Mutual Funds and Stocks. "
        else:
            reasoning += "the system leaned towards higher-return assets like Stocks and Crypto to maximize growth potential. "

        # Sharpe interpretation
        if sharpe > 1.0:
            sharpe_text = "This indicates strong risk-adjusted performance."
        elif sharpe > 0.5:
            sharpe_text = "This indicates moderate but acceptable risk-adjusted performance."
        else:
            sharpe_text = "This suggests the portfolio takes relatively high risk for its reward."

        # Key allocations
        top_allocs = sorted(allocations, key=lambda x: x["percent"], reverse=True)[:2]
        key_assets = ", ".join([a["asset"] for a in top_allocs])

        return (
            reasoning
            + f"Top allocations were made to **{key_assets}**, "
            + f"driven by their predicted returns and market sentiment. "
            + sharpe_text
        )


# -----------------------------
# Advisory Pipeline
# -----------------------------
class AdvisoryPipeline:
    def __init__(self):
        self.profiler = RiskProfiler()
        self.sentiment = SentimentAnalyzer()
        self.forecaster = MarketForecaster()
        self.optimizer = PortfolioOptimizer()
        self.explainer = ExplainabilityEngine()

    def run(self, user_input, price_df, news_texts=None, amount=10000):
        # Risk score
        risk_score = self.profiler.score(
            user_input.get("risk_tolerance", "medium"),
            user_input.get("investment_horizon", 3),
            user_input.get("savings_to_income", None)
        )

        # Sentiment
        sentiment_signals = {}
        if news_texts:
            for asset, texts in news_texts.items():
                sentiment_signals[asset] = np.mean(self.sentiment.score_texts(texts)) if texts else 0.0

        # Forecasting
        forecasts = self.forecaster.batch_forecast(price_df)
        combined = {}
        for a, f in forecasts.items():
            adj = f["expected_return"] + 0.5 * sentiment_signals.get(a, 0)
            combined[a] = {"expected_return": adj, "volatility": f["volatility"]}

        tickers = list(price_df.columns)
        returns_df = price_df.pct_change().dropna()
        cov = returns_df.cov().values
        exp_vec = np.array([combined[t]["expected_return"] for t in tickers])

        bounds = [(0, 0.6 if risk_score > 0.6 else 0.4 + 0.2 * risk_score)] * len(tickers)
        opt_res = self.optimizer.maximize_sharpe(exp_vec, cov, bounds=bounds)

        allocations = []
        for t, w in zip(tickers, opt_res["weights"]):
            allocations.append({
                "asset": t,
                "percent": float(w) * 100,
                "amount": float(w) * amount,
                "expected_return": combined[t]["expected_return"],
                "volatility": combined[t]["volatility"]
            })

        portfolio_metrics = {
            "expected_return": opt_res["return"],
            "volatility": opt_res["volatility"],
            "sharpe": opt_res["sharpe"],
            "risk_score": risk_score
        }

        explanation = self.explainer.explain(user_input, portfolio_metrics, allocations)

        return {"portfolio_metrics": portfolio_metrics, "allocations": allocations, "explanation": explanation}




# -----------------------------
# FastAPI Layer
# -----------------------------

app = FastAPI(title="AI Portfolio Advisory System")


def make_json_serializable(obj):
    if isinstance(obj, dict):
        return {k: make_json_serializable(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [make_json_serializable(v) for v in obj]
    if isinstance(obj, tuple):
        return [make_json_serializable(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    if isinstance(obj, np.bool_):
        return bool(obj)
    return obj


class UserInput(BaseModel):
    amount: float = Field(..., gt=0)
    investment_horizon: int = Field(..., ge=1, le=50)
    risk_tolerance: str
    goal: str

    @field_validator("risk_tolerance")
    @classmethod
    def validate_risk(cls, v):
        v = v.lower()
        if v not in {"low", "medium", "high"}:
            raise ValueError("risk_tolerance must be low, medium, or high")
        return v

    @field_validator("goal")
    @classmethod
    def validate_goal(cls, v):
        v = v.lower()
        if v not in {"growth", "income", "balanced"}:
            raise ValueError("goal must be growth, income, or balanced")
        return v


def generate_sample_data():
    dates = pd.date_range(end=pd.Timestamp.today(), periods=500, freq="B")
    np.random.seed(0)
    return pd.DataFrame({
        "MutualFunds": 100 * np.cumprod(1 + np.random.normal(0.0002, 0.001, len(dates))),
        "Stocks": 50 * np.cumprod(1 + np.random.normal(0.0005, 0.02, len(dates))),
        "FD": 100 * np.cumprod(1 + np.random.normal(0.00005, 0.0001, len(dates))),
        "Crypto": 10 * np.cumprod(1 + np.random.normal(0.001, 0.05, len(dates))),
    }, index=dates)


@app.get("/")
def home():
    return {"message": "Portfolio AI Running"}


@app.post("/analyze")
def analyze(user: UserInput):

    price_df = generate_sample_data()

    news = {
        "Stocks": ["Market optimistic"],
        "Crypto": ["Crypto bullish"],
        "MutualFunds": ["Stable inflows"],
        "FD": ["Interest rates stable"]
    }

    pipeline = AdvisoryPipeline()

    results = pipeline.run(
        {
            "investment_horizon": user.investment_horizon,
            "risk_tolerance": user.risk_tolerance,
            "goal": user.goal
        },
        price_df,
        news_texts=news,
        amount=user.amount
    )

    return make_json_serializable(results)
